### ISSUE TITLE
write a python program to swap two numbers

### ISSUE THREAD

**Issue by gauriiighadge** [gauriiighadge/HactoberFest2023#1]

**Comment by GhadgeGauri** [comment]
Please assign this to me

**Comment by GhadgeGauri** [comment]
pls assign me

**Comment by CDT-PRATEEK** [comment]
is this issue ressolved? can you asssign this to me?

**Comment by CDT-PRATEEK** [comment]
thankyou so much. can you please mark this as "Hacktoberfest-accepted"

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under hacktoberfest23.

**Comment by gauriiighadge** [comment]
--
