### ISSUE TITLE
a prgram that give the reverse of given input

### ISSUE THREAD

**Issue by R0Y15** [gauriiighadge/HactoberFest2023#11]
I'd like to contribute to this project, please assign this to me.

**Comment by adityakhevaria** [comment]
I would like to contribute to this repository. Assign this to me

**Comment by Mohd786-hub** [comment]
please assign this to me so that i contribute to this hactoberfest 2023 . i have good DSA knowledge and you can also check my projects in my repositories.

**Comment by Tankans** [comment]
please assign this to me so that i contribute to this hactoberfest 2023 . I like to contribute in this DSA problem

**Comment by kashyapanjali** [comment]
please assign this to me so that i contribute in this hactoberfest2023.

**Comment by Ved-Prakash-74** [comment]
Please assign me this task so that i can contribute

**Comment by AnudeepKK** [comment]
Hey I also want to contribute. So requesting you to assign me.

**Comment by sumitverma107** [comment]
Hi @gauriiighadge please assign it to me,i would put all my expeties in this.

**Comment by AYUSHSURYAVANSHI** [comment]
I'd like to contribute to this project, please assign this to me

**Comment by aniket-singh-01** [comment]
hey this is my first contibution . please assign and do the necessary steps.

**Comment by vedali29** [comment]
can you assign it to me? I would also look for time, and space complexity. please assign it to me

**Comment by AhanaDatta59** [comment]
Respected Sir,
kindly assign me with this task. I can assure you excellent results within a minimum timeframe

**Comment by priyanka0921** [comment]
@gauriiighadge  can u assign me for this Issue I will like to solve this and also added in hacktoberfest-2023 ?

**Comment by Mr-krishn** [comment]
please assign me this problem @gauriiighadge

**Comment by Severus25** [comment]
I'd like to contribute to this project, please assign this to me. I am  well versed in DSA and C/C++.
Thanks! @gauriiighadge
