### ISSUE TITLE
Check even or odd

### ISSUE THREAD

**Issue by Shorya7** [gauriiighadge/HactoberFest2023#14]
I want to add the code to check if the given number is odd or even in C++ under hactoberfest2023

**Comment by adityakhevaria** [comment]
@gauriiighadge Assign this to me.

**Comment by theyashvi** [comment]
is this issue ressolved? can you asssign this to me?

**Comment by aditya-bagla** [comment]
I updated the odd_or_even.cpp & created a pull request. 
its a code to check the number given by user is even or odd. 
Can you please assign to me and accept the pull request @gauriiighadge @GhadgeGauri

**Comment by satyendra9580** [comment]
can you assign me this, this is veru easy , i can do in ten minutes. please.

**Comment by Jugnu-Gupta** [comment]
hey could you please assign me this task i would like to contribute
