### ISSUE TITLE
python program to find HCF or GCD

### ISSUE THREAD

**Issue by harshsingh32** [gauriiighadge/HactoberFest2023#23]
Please consider this issue under hacktoberfest23. I would like to work on this issue, please assign this issue to me under hacktoberfest23.

**Comment by Mohd786-hub** [comment]
please assign this to me so that i contribute to this hactoberfest 2023 . i have good DSA knowledge and you can also check my projects in my repositories.

**Comment by MKD2002** [comment]
please assign this to me with the hactoberfest tag

**Comment by harshsingh32** [comment]
@gauriiighadge please assign this issue to me under hacktoberfest23, I would like to work on this issue.

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by princikarai** [comment]
Hi @gauriiighadge 
I would like to add code to find HCF or GCD .
Please assign me this issue under Hactoberfest 2023.
Thank You.
