### ISSUE TITLE
python program to check Armstrong Number

### ISSUE THREAD

**Issue by harshsingh32** [gauriiighadge/HactoberFest2023#24]
Please consider this issue under hacktoberfest23. I would like to work on this issue, please assign this issue to me under hacktoberfest23.

**Comment by Mohd786-hub** [comment]
please assign this to me so that i contribute to this hactoberfest 2023 . i have good DSA knowledge and you can also check my projects in my repositories.

**Comment by harshsingh32** [comment]
@gauriiighadge please assign this issue to me under hacktoberfest23, I would like to work on this issue.

**Comment by Ved-Prakash-74** [comment]
Please assign me this task so that i can contribute

**Comment by MohammadRehanPatel** [comment]
hey @gauriiighadge , please assign this issue to me

**Comment by princikarai** [comment]
Hi @gauriiighadge,
I would like to add  python program to check Armstrong Number code.
Please assign me this issue under Hactoberfest 2023.
Thank You.
