### ISSUE TITLE
python program to count the occurrence of an Item in a List

### ISSUE THREAD

**Issue by harshsingh32** [gauriiighadge/HactoberFest2023#25]
Please consider this issue under hacktoberfest23. I would like to work on this issue, please assign this issue to me under hacktoberfest23.

**Comment by harshsingh32** [comment]
@gauriiighadge please assign this issue to me under hacktoberfest23, I would like to work on this issue.

**Comment by Ved-Prakash-74** [comment]
Please assign me this task so that i can contribute

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by AhanaDatta59** [comment]
Respected Sir,  kindly assign me with this task. I can assure you excellent results within a minimum timeframe
