### ISSUE TITLE
write a python program for Extended Euclidean algorithm.

### ISSUE THREAD

**Issue by harshsingh32** [gauriiighadge/HactoberFest2023#26]
Please consider this issue under hacktoberfest23. I would like to work on this issue, please assign this issue to me under hacktoberfest23.

**Comment by slaughterhectic** [comment]
I would like to work on this issue can you assign me this?

**Comment by harshsingh32** [comment]
@gauriiighadge please assign this issue to me under hacktoberfest23

**Comment by sumitverma107** [comment]
HI @gauriiighadge please assign this to me,love to contribute with you on this project.

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by AhanaDatta59** [comment]
Respected Sir, kindly assign me with this task. I can assure you excellent results within minimum time
